GO_EASY_ON_ME = 1

TWEAK_NAME = Faith
Faith_FILES = Faith.m $(wildcard Controllers/*.m) $(wildcard Controllers/Loader/*.m)
Faith_CFLAGS = -fobjc-arc
Faith_FRAMEWORKS = UIKit
Faith_PRIVATE_FRAMEWORKS = MediaRemote

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
