BUNDLE_NAME = FaithPreferences
FaithPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
FaithPreferences_FRAMEWORKS = UIKit
FaithPreferences_PRIVATE_FRAMEWORKS = Preferences
FaithPreferences_INSTALL_PATH = /Library/PreferenceBundles
FaithPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
